<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.chuanjie.platform</groupId>
        <artifactId>cj-platform-server</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>cj-module-platform-control</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>cj-module-platform-control-api</module>
        <module>cj-module-platform-control-biz</module>
    </modules>
</project>
