-- S0 基线迁移：建立脚手架占位表，证明 Flyway 可用。
-- 正式业务表从 S1 起按域前缀新增，禁止堆入无前缀大杂烩。
-- 语法兼顾 PostgreSQL 与 H2(PostgreSQL mode)。

CREATE TABLE IF NOT EXISTS platform_schema_marker (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remark      VARCHAR(128) NOT NULL DEFAULT 's0-baseline',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_schema_marker IS 'S0 脚手架占位表，无业务含义，可在后续清理';
COMMENT ON COLUMN platform_schema_marker.id IS '主键';
COMMENT ON COLUMN platform_schema_marker.remark IS '备注';
COMMENT ON COLUMN platform_schema_marker.create_time IS '创建时间';
