-- S1-01：身份底座表（用户/组织/岗位/角色/菜单关联）
-- 语法兼顾 PostgreSQL 与 H2(PostgreSQL mode)；字段均 COMMENT。

CREATE TABLE IF NOT EXISTS platform_dept (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     BIGINT NOT NULL DEFAULT 0,
    name          VARCHAR(64) NOT NULL,
    sort_no       INT NOT NULL DEFAULT 0,
    status        VARCHAR(16) NOT NULL DEFAULT 'active',
    creator       VARCHAR(64),
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater       VARCHAR(64),
    update_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       BOOLEAN NOT NULL DEFAULT FALSE,
    version       INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE platform_dept IS '组织部门树';
COMMENT ON COLUMN platform_dept.id IS '主键';
COMMENT ON COLUMN platform_dept.parent_id IS '上级部门 ID，根为 0';
COMMENT ON COLUMN platform_dept.name IS '部门名称';
COMMENT ON COLUMN platform_dept.sort_no IS '同级排序，越小越靠前';
COMMENT ON COLUMN platform_dept.status IS '状态：active/disabled';
COMMENT ON COLUMN platform_dept.creator IS '创建人';
COMMENT ON COLUMN platform_dept.create_time IS '创建时间';
COMMENT ON COLUMN platform_dept.updater IS '更新人';
COMMENT ON COLUMN platform_dept.update_time IS '更新时间';
COMMENT ON COLUMN platform_dept.deleted IS '逻辑删除';
COMMENT ON COLUMN platform_dept.version IS '乐观锁版本';

CREATE TABLE IF NOT EXISTS platform_post (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64) NOT NULL,
    name          VARCHAR(64) NOT NULL,
    sort_no       INT NOT NULL DEFAULT 0,
    status        VARCHAR(16) NOT NULL DEFAULT 'active',
    creator       VARCHAR(64),
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater       VARCHAR(64),
    update_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       BOOLEAN NOT NULL DEFAULT FALSE,
    version       INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE platform_post IS '岗位';
COMMENT ON COLUMN platform_post.id IS '主键';
COMMENT ON COLUMN platform_post.code IS '岗位编码，唯一（未删除范围内）';
COMMENT ON COLUMN platform_post.name IS '岗位名称';
COMMENT ON COLUMN platform_post.sort_no IS '排序';
COMMENT ON COLUMN platform_post.status IS '状态：active/disabled';
COMMENT ON COLUMN platform_post.creator IS '创建人';
COMMENT ON COLUMN platform_post.create_time IS '创建时间';
COMMENT ON COLUMN platform_post.updater IS '更新人';
COMMENT ON COLUMN platform_post.update_time IS '更新时间';
COMMENT ON COLUMN platform_post.deleted IS '逻辑删除';
COMMENT ON COLUMN platform_post.version IS '乐观锁版本';

CREATE TABLE IF NOT EXISTS platform_role (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64) NOT NULL,
    name          VARCHAR(64) NOT NULL,
    remark        VARCHAR(256),
    status        VARCHAR(16) NOT NULL DEFAULT 'active',
    data_scope    VARCHAR(32) NOT NULL DEFAULT 'SELF',
    creator       VARCHAR(64),
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater       VARCHAR(64),
    update_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       BOOLEAN NOT NULL DEFAULT FALSE,
    version       INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE platform_role IS '角色';
COMMENT ON COLUMN platform_role.id IS '主键';
COMMENT ON COLUMN platform_role.code IS '角色编码';
COMMENT ON COLUMN platform_role.name IS '角色名称';
COMMENT ON COLUMN platform_role.remark IS '备注';
COMMENT ON COLUMN platform_role.status IS '状态：active/disabled';
COMMENT ON COLUMN platform_role.data_scope IS '数据范围：SELF/DEPT/ALL（S1-02 落地校验）';
COMMENT ON COLUMN platform_role.creator IS '创建人';
COMMENT ON COLUMN platform_role.create_time IS '创建时间';
COMMENT ON COLUMN platform_role.updater IS '更新人';
COMMENT ON COLUMN platform_role.update_time IS '更新时间';
COMMENT ON COLUMN platform_role.deleted IS '逻辑删除';
COMMENT ON COLUMN platform_role.version IS '乐观锁版本';

CREATE TABLE IF NOT EXISTS platform_user (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(64) NOT NULL,
    password_hash     VARCHAR(128) NOT NULL,
    display_name      VARCHAR(64) NOT NULL,
    mobile            VARCHAR(32),
    email             VARCHAR(128),
    user_type         VARCHAR(32) NOT NULL DEFAULT 'INTERNAL',
    status            VARCHAR(16) NOT NULL DEFAULT 'active',
    dept_id           BIGINT,
    external_idp      VARCHAR(64),
    external_subject  VARCHAR(128),
    creator           VARCHAR(64),
    create_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater           VARCHAR(64),
    update_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    version           INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE platform_user IS '平台用户（身份主数据）';
COMMENT ON COLUMN platform_user.id IS '主键';
COMMENT ON COLUMN platform_user.username IS '登录账号';
COMMENT ON COLUMN platform_user.password_hash IS '密码哈希（BCrypt），禁止明文';
COMMENT ON COLUMN platform_user.display_name IS '显示名';
COMMENT ON COLUMN platform_user.mobile IS '手机号';
COMMENT ON COLUMN platform_user.email IS '邮箱';
COMMENT ON COLUMN platform_user.user_type IS '身份类型：INTERNAL/ENTREPRENEUR/SUPPLIER';
COMMENT ON COLUMN platform_user.status IS '状态：active/disabled';
COMMENT ON COLUMN platform_user.dept_id IS '所属部门 ID';
COMMENT ON COLUMN platform_user.external_idp IS '外部 IdP 标识预留（如 casdoor），空表示本地账号';
COMMENT ON COLUMN platform_user.external_subject IS '外部主体唯一标识预留，与 IdP 映射';
COMMENT ON COLUMN platform_user.creator IS '创建人';
COMMENT ON COLUMN platform_user.create_time IS '创建时间';
COMMENT ON COLUMN platform_user.updater IS '更新人';
COMMENT ON COLUMN platform_user.update_time IS '更新时间';
COMMENT ON COLUMN platform_user.deleted IS '逻辑删除';
COMMENT ON COLUMN platform_user.version IS '乐观锁版本';

CREATE TABLE IF NOT EXISTS platform_user_role (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_user_role IS '用户-角色关联';
COMMENT ON COLUMN platform_user_role.id IS '主键';
COMMENT ON COLUMN platform_user_role.user_id IS '用户 ID';
COMMENT ON COLUMN platform_user_role.role_id IS '角色 ID';
COMMENT ON COLUMN platform_user_role.create_time IS '创建时间';

CREATE TABLE IF NOT EXISTS platform_user_post (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    post_id       BIGINT NOT NULL,
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_user_post IS '用户-岗位关联';
COMMENT ON COLUMN platform_user_post.id IS '主键';
COMMENT ON COLUMN platform_user_post.user_id IS '用户 ID';
COMMENT ON COLUMN platform_user_post.post_id IS '岗位 ID';
COMMENT ON COLUMN platform_user_post.create_time IS '创建时间';

CREATE TABLE IF NOT EXISTS platform_menu (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id         BIGINT NOT NULL DEFAULT 0,
    name              VARCHAR(64) NOT NULL,
    type              VARCHAR(16) NOT NULL DEFAULT 'MENU',
    path              VARCHAR(256),
    permission_code   VARCHAR(128),
    sort_no           INT NOT NULL DEFAULT 0,
    status            VARCHAR(16) NOT NULL DEFAULT 'active',
    creator           VARCHAR(64),
    create_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater           VARCHAR(64),
    update_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    version           INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE platform_menu IS '菜单/按钮权限资源（S1-02 完善校验）';
COMMENT ON COLUMN platform_menu.id IS '主键';
COMMENT ON COLUMN platform_menu.parent_id IS '上级菜单 ID，根为 0';
COMMENT ON COLUMN platform_menu.name IS '菜单或按钮名称';
COMMENT ON COLUMN platform_menu.type IS '类型：DIR/MENU/BUTTON';
COMMENT ON COLUMN platform_menu.path IS '前端路由 path';
COMMENT ON COLUMN platform_menu.permission_code IS '权限码，如 system:user:list';
COMMENT ON COLUMN platform_menu.sort_no IS '排序';
COMMENT ON COLUMN platform_menu.status IS '状态：active/disabled';
COMMENT ON COLUMN platform_menu.creator IS '创建人';
COMMENT ON COLUMN platform_menu.create_time IS '创建时间';
COMMENT ON COLUMN platform_menu.updater IS '更新人';
COMMENT ON COLUMN platform_menu.update_time IS '更新时间';
COMMENT ON COLUMN platform_menu.deleted IS '逻辑删除';
COMMENT ON COLUMN platform_menu.version IS '乐观锁版本';

CREATE TABLE IF NOT EXISTS platform_role_menu (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT NOT NULL,
    menu_id       BIGINT NOT NULL,
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE platform_role_menu IS '角色-菜单关联';
COMMENT ON COLUMN platform_role_menu.id IS '主键';
COMMENT ON COLUMN platform_role_menu.role_id IS '角色 ID';
COMMENT ON COLUMN platform_role_menu.menu_id IS '菜单 ID';
COMMENT ON COLUMN platform_role_menu.create_time IS '创建时间';

-- ---------------------------------------------------------------------------
-- S1-01 开发初始化种子（写在迁移里，禁止 Java 硬编码再插）
-- 默认账号：admin / Admin@123（BCrypt）；正式环境务必改密或禁用此账号
-- 使用 WHERE NOT EXISTS，避免重复执行时重复插入（兼容 PG / H2）
-- ---------------------------------------------------------------------------

INSERT INTO platform_dept (parent_id, name, sort_no, status, creator, updater, deleted, version)
SELECT 0, '创界总部', 0, 'active', 'system', 'system', FALSE, 0
WHERE NOT EXISTS (
    SELECT 1 FROM platform_dept d
    WHERE d.deleted = FALSE AND d.parent_id = 0 AND d.name = '创界总部'
);

INSERT INTO platform_role (code, name, remark, status, data_scope, creator, updater, deleted, version)
SELECT 'ADMIN', '系统管理员', 'S1 默认全量角色', 'active', 'ALL', 'system', 'system', FALSE, 0
WHERE NOT EXISTS (
    SELECT 1 FROM platform_role r
    WHERE r.deleted = FALSE AND r.code = 'ADMIN'
);

INSERT INTO platform_post (code, name, sort_no, status, creator, updater, deleted, version)
SELECT 'P_ADMIN', '管理员', 0, 'active', 'system', 'system', FALSE, 0
WHERE NOT EXISTS (
    SELECT 1 FROM platform_post p
    WHERE p.deleted = FALSE AND p.code = 'P_ADMIN'
);

INSERT INTO platform_user (
    username, password_hash, display_name, user_type, status, dept_id,
    creator, updater, deleted, version
)
SELECT
    'admin',
    -- Admin@123 的 BCrypt；勿改成明文
    '$2a$10$c7aYJqxIeZbdPbF6ETWFo.F8infVfl9TrBZzZ3cgh3wHZxNaBz2pu',
    '系统管理员',
    'INTERNAL',
    'active',
    (SELECT d.id FROM platform_dept d
     WHERE d.deleted = FALSE AND d.parent_id = 0 AND d.name = '创界总部'
     ORDER BY d.id LIMIT 1),
    'system',
    'system',
    FALSE,
    0
WHERE NOT EXISTS (
    SELECT 1 FROM platform_user u
    WHERE u.deleted = FALSE AND u.username = 'admin'
);

INSERT INTO platform_user_role (user_id, role_id, create_time)
SELECT u.id, r.id, CURRENT_TIMESTAMP
FROM platform_user u
CROSS JOIN platform_role r
WHERE u.deleted = FALSE AND u.username = 'admin'
  AND r.deleted = FALSE AND r.code = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM platform_user_role ur
      WHERE ur.user_id = u.id AND ur.role_id = r.id
  );
